#!/usr/bin/env bash
set -euo pipefail

# updateVersion.sh
# Reads version-*.txt (generated by generateVersion.sh) and updates project files:
# - version.py (__version__ = "...")
# Usage: ./scripts/updateVersion.sh

# Find version file
VERSION_FILE=$(ls version-*.txt 2>/dev/null | head -n1 || true)
if [[ -z "$VERSION_FILE" ]]; then
  echo "No version-*.txt found. Using fallback values." >&2
  VERSION="0.0.2-fallback"
else
  echo "Reading version info from $VERSION_FILE"
  # shellcheck disable=SC2002
  VERSION=$(grep '^version=' "$VERSION_FILE" | head -n1 | cut -d'=' -f2-)
fi

# Fallback
VERSION=${VERSION:-"0.0.2-fallback"}

echo "Updating src_service/version.py with version: $VERSION"
# Update src_service/version.py
cat > src_service/version.py <<EOF
"""Version information for the door controller."""

__version__ = "$VERSION"
EOF

echo "Version update complete."
