# updateVersion.ps1
# Reads version-*.txt (generated by generateVersion.ps1) and updates project files:
# - version.py (__version__ = "...")
# Usage: .\scripts\updateVersion.ps1

if (Test-Path "version-*.txt") {
    Write-Host "Found existing version-*.txt file(s), reading version information from it."
    $versionFile = Get-ChildItem "version-*.txt" | Select-Object -First 1
    $content = Get-Content $versionFile.FullName
    $VERSION = ($content | Where-Object { $_ -match "^version=" }) -replace "^version=", ""
} else {
    Write-Host "No existing version-*.txt file found, using fallback version information."
    $VERSION = "0.0.2-fallback"
}

Write-Host "Using version: $VERSION"

Write-Host "Updating src_service/version.py with version: $VERSION"
# Update src_service/version.py
$versionContent = @"
"""Version information for the door controller."""

__version__ = "$VERSION"
"@

Set-Content -Path "src_service/version.py" -Value $versionContent -NoNewline
Write-Host "Version updated successfully to $VERSION"
